Cshell : execute_clock.o clear_screen.o exec.o execute_cd.o execute_remindme.o get_input2.o execute_ls.o pinfo.o execute_echo.o generate_commandline.o execute_pwd.o shell_2.o execute_lsl.o
	gcc -o Cshell execute_clock.o clear_screen.o exec.o execute_cd.o execute_remindme.o get_input2.o execute_ls.o pinfo.o execute_echo.o generate_commandline.o execute_pwd.o shell_2.o execute_lsl.o

execute_clock.0 : execute_clock.c
	gcc -c execute_clock.c

clear_screen.o : clear_screen.c
	gcc -c clear_screen.c

exec.o : exec.c
	gcc -c exec.c

execute_cd.o : execute_cd.c
	gcc -c execute_cd.c

execute_remindme.o : execute_remindme.c
	gcc -c execute_remindme.c

get_input2.o : get_input2.c
	gcc -c get_input2.c

execute_ls.o : execute_ls.c
	gcc -c execute_ls.c

execute_lsl.o : execute_lsl.c
	gcc -c execute_lsl.c	

pinfo.o : pinfo.c
	gcc -c pinfo.c

execute_echo.o : execute_echo.c
	gcc -c execute_echo.c

generate_commandline.o : generate_commandline.c
	gcc -c generate_commandline.c

execute_pwd.o : execute_pwd.c
	gcc -c execute_pwd.c

shell_2.o : shell_2.c
	gcc -c shell_2.c

clean : 
	rm -f execute_clock.o clear_screen.o exec.o execute_cd.o execute_remindme.o get_input2.o execute_ls.o pinfo.o execute_echo.o generate_commandline.o execute_pwd.o shell_2.o execute_lsl.o Cshell